apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  flask-secret-key: "segunda_contrasena_super_secreta"
  mongo-uri: "mongodb://admin:contrasena_super_secreta_de_mongo@mongo-service:27017/galeria_db?authSource=admin"